countries = ['Angola'] #  Manipulable
dataFrameCols = ['Region', 'Country name', 'Language', 'Time (ms)'] #   Mejor no modificar...
newData = {'Region': "", 'Country name': "", 'Language':"", 'Time (ms)': ""} #   No modificar...